### ISSUE TITLE
translation of New Entry

### ISSUE THREAD

**Issue by TWART016** [TandoorRecipes/recipes#1777]
### Tandoor Version

1.2.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I use german UI. Inside shopping list the translation is not made for button `New Entry`
![image](https://user-images.githubusercontent.com/29805669/167162728-46644c4f-7c54-4872-9f8b-a0f203d5b11d.png)

**Comment by vabene1111** [comment]
fixed in next release (its not translatable)

**Comment by TWART016** [comment]
In which version is this fixed? In 1.2.5 and develop it is still wrong.

**Comment by vabene1111** [comment]
It's not translate but it can be, that's what I fixed. Translation mostly come from the community and take some time.
