### ISSUE TITLE
System menu item is working incorrectly

### ISSUE THREAD

**Issue by casimpunkt** [TandoorRecipes/recipes#3399]
### Tandoor Version

1.5.21

### Setup

Synology

### Reverse Proxy

No reverse proxy

### Bug description

Since the update from 1.5.20 to 1.5.21, when calling "System" you get a server error (500). This worked in version 1.5.20.

**Comment by dyxen** [comment]
Its the same on my system. It was working on 1.5.20, on 1.5.21 i get Server Error (500)

Using unRaid docker and swag reverse proxy.

**Comment by rubenixnagios** [comment]
same, no extra info on logs, running on debian 12 Docker version 27.3.1 & Docker Compose version v2.29.7

**Comment by triayak** [comment]
same. Just finished setting it up for the first time using docker compose behind traefik, trying to wrap my head around what i did wrong. Without DEBUG=0 in the .env file i get an error page for "Error 111 connecting to None:6379. Connection refused.". Seems like it wants to connect to a nonexistant redis instance? Also the web_recipes container logs the following Python errors: 

web_recipes_1    | Internal Server Error: /system/
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
web_recipes_1    |     sock = self.retry.call_with_retry(
web_recipes_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
web_recipes_1    |     return do()
web_recipes_1    |            ^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
web_recipes_1    |     lambda: self._connect(), lambda error: self.disconnect(error)
web_recipes_1    |             ^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
web_recipes_1    |     raise err
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
web_recipes_1    |     sock.connect(socket_address)
web_recipes_1    | ConnectionRefusedError: [Errno 111] Connection refused
web_recipes_1    |
web_recipes_1    | During handling of the above exception, another exception occurred:
web_recipes_1    |
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
web_recipes_1    |     response = get_response(request)
web_recipes_1    |                ^^^^^^^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
web_recipes_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_recipes_1    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/cookbook/views/views.py", line 360, in system
web_recipes_1    |     total_stats = ['All', int(r.get('api:request-count'))]
web_recipes_1    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/commands/core.py", line 1822, in get
web_recipes_1    |     return self.execute_command("GET", name, keys=[name])
web_recipes_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
web_recipes_1    |     return self._execute_command(*args, **options)
web_recipes_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
web_recipes_1    |     conn = self.connection or pool.get_connection(command_name, **options)
web_recipes_1    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
web_recipes_1    |     connection.connect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
web_recipes_1    |     raise ConnectionError(self._error_message(e))
web_recipes_1    | redis.exceptions.ConnectionError: Error 111 connecting to None:6379. Connection refused.

**Comment by vabene1111** [comment]
thanks for the reports, i forgot a check, fixed in the next version

**Comment by syphernl** [comment]
Version 1.5.22 still shows a HTTP 500 on the system page.

**Comment by rubenixnagios** [comment]
> Version 1.5.22 still shows a HTTP 500 on the system page.

same, docker version

**Comment by rubenixnagios** [comment]
any chance to reopen this? @vabene1111

**Comment by vabene1111** [comment]
sure, mention is not needed, I look at issues but I do not do this full time so responses might take some time, especially since tandoor is fully usable without the system page (too be honest I am amazed by how many people report this issue while others go unnoticed for month 😂 )

will be fixed

**Comment by rubenixnagios** [comment]
Tx mate no worries at all, nice work!! been using Untare for so long but seems project has been abandoned by author, now I just discovered Kitshn and love it. In the settings page, under Servers its shows version 'unknown' --> thats why I noticed error 500 in status page :sweat_smile: needed to find android solution for family members!! Love Tandoor :heart:

**Comment by BobWs** [comment]
Thx! Will see the update when fixed!

**Comment by ballinger** [comment]
Also thanx! Eager to get this working :)

**Comment by dominiclesinski** [comment]
I'm getting more verbose info with debug enabled maybe this will help fix the issue: 

Exception Value:	
cannot access local variable 'api_stats' where it is not associated with a value
Exception Location:	/opt/recipes/cookbook/views/views.py, line 391, in system

**Comment by lgwapnitsky** [comment]
getting the same thing. Also errors with OIDC/Keycloak, and may be related.

Tried a fresh install on another system, but vue dependencies are failing, primarily node-gyp.

Waiting on fixes :)

**Comment by vabene1111** [comment]
I think I fixed it for real this time :) pushed a beta update if anyone wants to try it out.

**Comment by BobWs** [comment]
Yes it's working again! Thx!

![Screen_Shot](https://github.com/user-attachments/assets/2ea68a76-340e-44a4-a1d6-5e7ed8334860)

**Comment by lgwapnitsky** [comment]
I did a pull yesterday when I got the email, and I still don't have
success. Should I try another pull later today?

**Comment by BobWs** [comment]
> Should I try another pull later today?

Yes, I guess it couldn't hurt to try antoher pull.
